### ISSUE TITLE
All branch triggers are wrongly counted on a single branch

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [raymak/vpn-recommendation-shield-study#68] opened 2018-10-15 14:47 UTC
**[Notes]:**
- Telemetry is also wrongly sent for triggering the doorhanger on other branches than the user is in. 
- The issue is also reproducible if you are in "control" branch by visiting triggering websites, waiting 10 minutes to pass, or triggering a captive portal notification. 

**[Affected versions]:**
- Firefox 62 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- The [VPN Recommendation Shield Study](https://bugzilla.mozilla.org/show_bug.cgi?id=1478770#c20) addon is installed on a clean new profile.
- Be in any variation branch.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Attempt to trigger the doorhanger for other branches. 
3. Navigate to the "about:config" page and observe the value of the following preferences:
- "extensions.vpn-recommendation-study-1_shield_mozilla_org.lastNotification"
- "extensions.vpn-recommendation-study-1_shield_mozilla_org.notificationCount" 

**[Expected result]:**
- The preferences are not displayed. 
 
**[Actual result]:**
- Triggers for other branches are counted.

**[Additional notes]:**
- This issue is also reproducible with the latest master build. 
- Attached a screen recording of the issue:

![rec of the issue - vpn shield](https://user-images.githubusercontent.com/37875464/46958282-280cb180-d0a2-11e8-9e8c-67919a1c90b4.gif)

**Comment by SoftVision-CarmenFat** [comment] 2018-10-16 12:28
Going further into this issue, we noticed that a new ping is generated and sent to the local server each time we visit one of the targeted websites.

![pings](https://user-images.githubusercontent.com/26000308/47016253-c9a20a80-d157-11e8-9d36-ad1a31ff9111.gif)

**Comment by raymak** [comment] 2018-10-16 15:39
This is expected behavior due to https://github.com/raymak/vpn-recommendation-shield-study/issues/42. In each branch, we collect data about all triggers, but only show the notification if the trigger matches the branch of the study. The notifications that result from triggers that do not match the branch that the user is in have a "is-shadow": "true" field. So, as long as you see this field in the ping, it means that it won't result in an actual notification and it is only for data collection and analysis purposes.

**Comment by SoftVision-CiprianMuresan** [comment] 2018-10-17 12:38
One concern here:

Aren't we spamming with pings a bit if things remain the way they are? Basically each visit on a targeted website sends a ping to the server. 
Aren't we risking to "muddy the waters" this way?

Shouldn't we send pings _only_ when the user would have been able to see a notification (5 pings total, across all branches)?

**Comment by raymak** [comment] 2018-10-17 16:30
This is a very valid concern that I'm thinking about.

**Comment by raymak** [comment] 2018-10-17 16:45
@jmcrosky @chrismore: 
Right now we send pings for raw triggers, including every visit to a streaming website (e.g. netflix, youtube), which is really too much. I would like to exclude raw triggers for our streaming and privacy hostname branches. I will keep it for catch-all and captive portal branches however, as those are less frequent, safer, and especially the captive portal branch provides us information about Firefox usage that we don't have in Telemetry. Let me know your opinion.

**Comment by chrismore** [comment] 2018-10-17 19:15
@raymak does not having all of the raw pings impact knowing the users who saw the trigger and the users who engaged with the trigger? Would we only have total counts and not pings with time series content? There is some benefit of having the triggers, because it would give us sense of how many times a user needs to be exposed to a trigger and a doorhanger to convert within 3 doorhanger attempts. 

Is the comment "which is really too much" associated with storage or cost or both? With 0.5% of users or maybe up to 1% of users, do we think that it will really be too much over the duration of the experiment?

**Comment by raymak** [comment] 2018-10-17 23:42
@chrismore we still we will still have (time-stamped) data about when the user would see the doorhanger with the throttling constraints in mind, but we will not know about every instance of a trigger, which most of the time does not lead to a doorhanger. 

Let me clarify with an example. If the user visits youtube.com 7 times on day 1 and 10 times on day 2, with the full data collection we would get a total of 17 pings for day 1 and day 2. With the lean data collection approach we would get one ping for day 1 and one ping for day 2, because the user see the actual doorhanger only once on day 1 and once on day 2. So we will still have time series data about doorhanger notifications, we just won't have data about every instance of visiting a streaming website.

I'm not sure if this is too much of a cost for our storage or not. I don't think it'll be unbearable for out Telemetry pipeline. It is too much based on our lean data collection approach. It just does not add much to our analysis. Again, we will still have pings that tell us about the doorhanger notifications and those are enough for our engagement analysis.

**Comment by jmccrosky** [comment] 2018-10-18 06:57
From an analysis perspective, logging the impressions (and counterfactual
impressions) of the doorhanger is adequate.

The only reasons I imagine we might need all the triggers logged are if we
want to know how many impressions would be created if the throttling were
relaxed, or to debug and make sure the trigger/throttling logic is working
correctly.

**Comment by raymak** [comment] 2018-10-18 23:32
Per #75, we no longer submit pings for raw triggers in the streaming-hostname and privacy-hostname branches. Therefore, visits to websites should not result in submission of pings with the field ```"message_type": "trigger"```.

**Comment by raymak** [comment] 2018-10-18 23:32
@SoftVision-CiprianMuresan please close this issue if you have no further objections.

**Comment by SoftVision-CiprianMuresan** [comment] 2018-10-19 10:56
I have verified that we no longer submit pings for raw triggers in streaming-hostname and privacy-hostname on Windows 10, Mac 10.13, and Arch Linux. As discussed above, catch-all and captive portal have remained unchanged.

**Closed by SoftVision-CiprianMuresan** 2018-10-19 10:56 UTC
Labels: QA, [QA]:Verified fixed
