### ISSUE TITLE
[catch-all] The doorhanger is not displayed after 10 minutes if the browser window is minimized

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [raymak/vpn-recommendation-shield-study#57] opened 2018-10-09 14:22 UTC
[Affected versions]:
- Firefox 62.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The [VPN Recommendation Shield Study](https://bugzilla.mozilla.org/show_bug.cgi?id=1478770#c20) addon is installed on a clean new profile.
- Be in the "catch-all" variant.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Minimize the browser window and wait 15 minutes.
3. Restore the browser window and observe the behavior.

[Expected result]:
- The doorhanger is displayed/triggered.

[Actual result]:
- No doorhanger is displayed.

[Notes]:
- The main concern here is that we count this case as "seen" by the user, but in fact, the user has not seen the doorhanger because the window was minimized when the trigger was supposed to happen.

**Comment by raymak** [comment] 2018-10-17 11:17
This should be fixed now.

**Comment by raymak** [comment] 2018-10-18 02:55
I cannot reproduce this on Mac 10.14. Is that the same for you? This helps me narrow down the problem.

**Comment by SoftVision-CiprianMuresan** [comment] 2018-10-18 15:39
I also can't reproduce the issue on Mac 10.14, but I can reproduce it on Mac 10.11, 10.12, and 10.13. It also seems to be reproducible on Arch Linux and not on Debian.

**Comment by stlhood** [comment] 2018-10-19 16:42
I'm not super worried about Arch Linux for this experiment, but it looks like ~50% of macOS users are still on 10.13 (High Sierra) so that's more concerning.

When we say it counts as "seen" does that mean it ends up in our metrics as someone who ignored or dismissed the doorhanger? Or does it simply mean that the doorhanger itself counts it as a failed attempt?

**Comment by raymak** [comment] 2018-10-19 22:38
It works fine for me in Arch linux.

**Comment by raymak** [comment] 2018-10-19 23:58
@stlhood : in our data it would look like a doorhanger that was never dismissed by the user. It will still get automatically dismissed if the user opens a new tab or window.

**Comment by stlhood** [comment] 2018-10-20 00:03
@raymak In that case I would not consider this a showstopper. We should fix it but I think we could proceed with launch on Monday, especially since we're starting with a small sample anyway...

**Closed** 2018-10-22 19:16 UTC
Labels: QA, [QA]:Verified fixed
